language: r
dist: xenial
cache: packages

r_packages:
  - covr

r_github_packages:
  - ropensci/geojsonlint

matrix:
  include:
    - r: oldrel
    - r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

addons:
  apt:
    sources:
      - sourceline: 'ppa:jeroen/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
    - libudunits2-dev
    - libv8-dev
    - libprotobuf-dev
    - libprotoc-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - protobuf-compiler
    - valgrind
    - libjq-dev
    - netcdf-bin

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: I7evcyFpHziA83/sYF1rK4u5GgcwxuLinNA50VmEgWpyOJNQnUOqp+oBjLMhOXy5Y3vdgNnqQ6ep3XA1rMWGzPd1LKdwiH4CpWRJAlsw1z5C5F/rLoYo5TeF+ZtmtG6AkvobdKgHJZgplNQaSfBXWC12BdK/gVraGkUSQXtKgMknXQbiS70QMtK0GczQ/EBYuIK506qeYGTydn20wLxQDZtKpJqXDmdl+BA2r3T51lYzDaE1I8hTimZYml3Q4hSk2QND6cmlkgGT03ptkYh/tdOE2mJmkypdIQnxAmv1fttbDRutDLsaXTtmmGEUI9v/IBnkwRvkX1SbfB7wEDCn60MtoNfpzDR0wbzXvBCKvDxTCmfL9B6k0wQjuPwIV6yuxUHFrPwvNO6O3EAd9MnfXp3vy/x0BVoidw5mZjBHgCKAuX7Hstb9cg4M8IIiwlzT9awEOPSV+ZsjWGarUmKlQmE9u91RqrkCoSL57RlwOqOECqkQxbEYx5CBS3onzsfbUd4xnxinEwvv1xB8tpjKlHUJAveOelvx0HBhxU+2VvmkmAXkehQS41b2Zi2FyBT5d33nzrRZh2Zb8W2GNXw2K3dGNkbUw6MXSFVuB3V59ZQgzgqkqxUHMSemh/+tcwqDP9h1Evv18jQHtODiozmzSk3SnDpj3BQ0poGLTyLQquY=

environment:
  global:
    _R_CHECK_FORCE_SUGGESTS_: false
